//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_player_operation : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 LeftStick
        {
            get
            {
                return SteamVR_Actions.player_operation_LeftStick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightStick
        {
            get
            {
                return SteamVR_Actions.player_operation_RightStick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTrigger
        {
            get
            {
                return SteamVR_Actions.player_operation_LeftTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGrip
        {
            get
            {
                return SteamVR_Actions.player_operation_LeftGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTrigger
        {
            get
            {
                return SteamVR_Actions.player_operation_RightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrip
        {
            get
            {
                return SteamVR_Actions.player_operation_RightGrip;
            }
        }
    }
}
